blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/design-to-release/cosmic/discussions/categories/q-a
    about: Use GitHub discussions for message-board style questions and discussions.
